config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions, only:      [:new, :create, :destroy]
  resources :microposts, only:    [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :contact_form, only: [:new] 

  root to: 'static_pages#home'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match 'signout', to: 'sessions#destroy', via: :delete
  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/contact_form', to: 'contact_form#send_email', via: :post

 

end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController

  def new
    @contact_form = ContactForm.new
  end

  def send_email
  	@contact_form = ContactForm.new(params[:contact_form])

  	if @contact_form.valid?
  	  NotificationsMailer.contact_form.deliver
  	  redirect_to root_path, notice: "Email sent, we'll get back to you"
  	else
  	  render :new, flash: "Please fill out all fields"
  	end
  end
end

app/views/contact_form/_contact_form.html.erb
<%= form_for @contact_form, url: contact_form_path do |f| %>
  <div class="fields">
  	<%= f.label :name %><br />
  	<%= f.text_field :name %>
  </div>
  <div class="field">
  	<%= f.label :email %><br />
  	<%= f.text_field :email %>
  </div>
  <div class="field">
  	<%= f.label :body %><br />
  	<%= f.text_area :body %>
  </div>
  <div class="actions">
  	<%= f.submit %>
  </div>
<% end %>

app/views/contact_form/new.html.erb
<h1>Give us feedback!</h1>

<%= render 'contact_form' %>
  